### DISCUSSION TITLE
Log files filling my harddrive

### DISCUSSION THREAD

**Discussion by ChrisNolan** [karrioapi/karrio#691] [General]
What do y'all do with your karrio log files?

I've noticed after a few weeks my 'karrio.worker' container for example has a log file that is 15% of the total available diskspace.  Whoops!

I'm thinking of editing my docker-compose.yml file and adding in the logging options to limit the size and do some rotation of the logs there.   e.g.

```yaml
services:
  your_service:
    image: your_image
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
```

So in the above case, each log file would cap out at 10 mb, and it would keep a history of 3 of them.

What have others done to manage this on their local installs?
