### ISSUE TITLE
Improving docker-compose.yml

### ISSUE THREAD

**Issue by MarcoWel** [karrioapi/karrio#311]
I would suggest adding the following values to the default docker/docker-compose.yml file to improve "out of the box" experience for new users trying to run karrio first time:

```yml
services:
  api:
    ...
    environment:
      ...
      USE_HTTPS: "False"
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_FROM_ADDRESS: ${EMAIL_FROM_ADDRESS}
```
