### ISSUE TITLE
Add CONN_MAX_AGE environment to docker-compose.yml

### ISSUE THREAD

**Issue by bosofluta44** [karrioapi/karrio#317]
**Is your feature request related to a problem? Please describe.**
I use the ElephantSQL server that handles databases. It has a limited amount of connections to a database. The current version of the app has CONN_MAX_AGE=500 variable. In this case, I usually get the `too many connections for role` error.

**Describe the solution you'd like**
I suggest adding the env variable that I could set in my docker-compose.yml file.
```
version: '3'

services:
  ***:
    container_name: ***
    image: karrio/server:2023.1.7
    restart: unless-stopped
    ports:
      - 5002:5002
    environment:
      CONN_MAX_AGE: "100"
```
